[env]
platform = espressif32 @ 7.0.1
framework = espidf
monitor_speed = 115200
extra_scripts = pre:tools/build_metadata.py, post:tools/pack_web_firmware.py

[env:esp32s3_r8n16]
board = esp32s3_r8n16
board_build.esp-idf.sdkconfig_path = sdkconfig.build.r8n16
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.r8n16"

[env:esp32s3_r8n8]
# Waveshare ESP32-S3-Zero
board = esp32s3_r8n8
board_build.esp-idf.sdkconfig_path = sdkconfig.build.r8n8
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.r8n8"
build_flags = -DRGB_LED_GPIO=21 -DRGB_LED_ORDER_RGB
