#include "portal_page.h"

const char *portal_page_html(void)
{
    static const char page[] =
        "<!doctype html><html><head><meta charset=utf-8><meta name=viewport "
        "content='width=device-width,initial-scale=1'><title>ESP32 VLESS Router</title>"
        "<style>body{font:16px system-ui;max-width:680px;margin:2rem auto;padding:0 "
        "1rem;color:#17212b}h1{color:#0b6e4f}fieldset{border:1px solid "
        "#ccd5df;border-radius:8px;margin:1rem 0;padding:1rem}label{display:block;margin:.65rem "
        "0}.hint{color:#59636e;font-size:.9rem}input,select{box-sizing:border-box;width:100%;"
        "padding:.6rem;margin-top:.2rem}.check{display:flex;align-items:center;gap:.4rem}.check input{width:auto;"
        "padding:0;margin:0}button{padding:.65rem "
        "1rem;background:#0b6e4f;color:white;border:0;border-radius:5px;font-weight:600}#status{"
        "margin-top:1rem}.dashboard{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,"
        "1fr));gap:.7rem;margin:1rem 0}.status-card{border:1px solid #ccd5df;border-radius:8px;"
        "padding:.8rem;background:#f8fafc}.status-card h2{font-size:.9rem;margin:0 0 .45rem;color:#0b6e4f}.status-card "
        "b,.status-card span{display:block;line-height:1.5}.status-card span{color:#59636e;font-size:.88rem}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,"
        "1fr));"
        "gap:1rem}.chart{border:1px solid #ccd5df;border-radius:8px;padding:.65rem}.chart h3{"
        "margin:0 0 .4rem;font-size:1rem}.chart "
        "canvas{display:block;width:100%;height:145px}</style>"
        "</head><body>"
        "<h1>ESP32 VLESS Router</h1><section id=network class=dashboard>Loading router status..."
        "</section><form "
        "id=f><fieldset><legend>Router Wi-Fi access point</legend><p class=hint>Saving these "
        "settings disconnects all clients. Reconnect using the new name, password, and gateway "
        "after saving.</p><label>AP "
        "name (SSID)<input id=ap_ssid maxlength=32 required></label><label>AP password<input "
        "id=ap_password type=password minlength=8 maxlength=64 placeholder='Leave blank to keep "
        "saved password'></label><label>Router IPv4 / downstream subnet<input id=ap_ip "
        "maxlength=15 placeholder='192.168.X.1'></label><p class=hint>Set the ESP32 LAN address "
        "such as 192.168.8.1 to move clients onto 192.168.8.x/24. The final octet must stay "
        "1.</p><button type=button id=save_ap>Save router "
        "Wi-Fi</button></fieldset><fieldset><legend>Portal administrator</legend><p class=hint>"
        "Username: <b>admin</b>. Change the factory password immediately.</p><label>Current "
        "password<input id=current_admin_password type=password autocomplete=current-password "
        "maxlength=64 required></label><label>New password<input id=new_admin_password "
        "type=password autocomplete=new-password minlength=12 maxlength=64 required></label>"
        "<button type=button id=save_admin_password>Change portal password</button></fieldset>"
        "<fieldset><legend>Upstream Wi-Fi</legend><label>Saved upstreams<select "
        "id=saved_upstreams><option value=''>No saved upstreams</option></select></label><label>Network<select "
        "id=net><option value=''>Scan networks...</option></select></label><label>SSID<input "
        "required name=ssid id=ssid maxlength=32></label><label>Password<input name=password "
        "id=password type=password maxlength=64 placeholder='Leave blank to keep the saved password for this SSID'></label>"
        "<label class=check><input name=open_network id=open_network type=checkbox>Open/public network (no password)</label>"
        "<p class=hint>Saving the same SSID again moves it to the top of the saved upstream list. The latest 10 upstream profiles are kept.</p>"
        "<button type=button id=scan>Scan Wi-Fi</button> <button type=button "
        "id=save_upstream>Save upstream Wi-Fi</button> <button type=button id=delete_upstream>Delete selected upstream</button></fieldset><fieldset><legend>VLESS "
        "(TCP)</legend><label>VLESS URI<input name=vless_uri id=vless_uri maxlength=255 "
        "placeholder='vless://UUID@host:port?encryption=none&type=tcp'></label><p class=hint>Paste "
        "a plain VLESS TCP URI, or fill in the fields below.</p><label>Server host/IP<input "
        "name=host id=host maxlength=127 placeholder='vpn.example.com'></label><label>Port<input "
        "name=port id=port type=number min=1 max=65535 placeholder='443'></label><label>UUID<input "
        "name=uuid id=uuid type=password autocomplete=off maxlength=47 placeholder='Saved UUID is "
        "hidden; leave blank to keep it'></label><label>DNS resolver hostname<input "
        "name=dns_resolver id=dns_resolver maxlength=253 placeholder='one.one.one.one (factory "
        "default)'></label><label class=check><input name=singmux_enabled id=singmux_enabled type=checkbox>"
        "Enable sing-box smux multiplex transport</label><p class=hint>Enable only when the VLESS "
        "server has sing-box multiplexing enabled. It shares one VLESS TCP session for transparent "
        "TCP streams and persistent UDP associations; disable it for servers without sing-box "
        "mux.</p><button type=button id=save_vless>Save VLESS</button></fieldset></form><p "
        "id=status></p><fieldset><legend>Firmware update</legend><p class=hint>Upload the "
        "application-only <code>-ota.bin</code> image produced by this project. The router "
        "verifies "
        "the ESP image, switches to it, then reboots. Do not upload the full <code>0x0</code> web-"
        "flash image here.</p><label>OTA firmware<input id=ota_file type=file accept=.bin "
        "required></label><button type=button id=install_ota>Install update and reboot</button>"
        "</fieldset><section class=metrics><div class=chart><h3 id=bandwidth_title>Routed payload bandwidth</h3>"
        "<canvas id=bandwidth_chart aria-label='Recent upload and download bandwidth'></canvas>"
        "<p class=hint id=bandwidth_summary>Collecting samples...</p></div><div class=chart><h3>"
        "Tunnel pressure</h3><canvas id=pressure_chart aria-label='Recent XUDP and smux pressure'>"
        "</canvas><p class=hint id=pressure_summary>Collecting samples...</p></div><div class=chart><h3>Chip temperature</h3><canvas id=temperature_chart aria-label='Recent chip temperature'></canvas><p class=hint id=temperature_summary>Collecting samples...</p></div><div class=chart><h3>CPU load by core</h3><canvas id=cpu_chart aria-label='Recent CPU load by core'></canvas><p class=hint id=cpu_summary>Collecting samples...</p></div></section><p "
        "class=hint "
        "id=version>Firmware: loading...</p>"
        "<script>const "
        "q=s=>document.querySelector(s),st=q('#status'),histories={vless:[],direct:[]},deviceHistory=[],historyLimit=60,rate=n=>(n/"
        "1024).toFixed(1)+' "
        "KiB/s',size=n=>(n/1024).toFixed(1)+' KiB';let currentConfig=null,scanInProgress=false,refreshInProgress=false;function syncOpenNetwork(){let open=q('#open_network').checked,p=q('#password');if(open){p.value='';p.disabled=true}else p.disabled=false}function renderSavedUpstreams(c){let s=q('#saved_upstreams'),n=c.upstream_networks||[],signature=JSON.stringify(n);if(s.dataset.upstreams===signature)return;let selected=s.value;s.options.length=0;s.add(new Option('Saved upstream profiles',''));n.forEach(x=>s.add(new Option(x.ssid+(x.open?' (open)':''),x.ssid)));s.value=n.some(x=>x.ssid===selected)?selected:(c.ssid||'');s.dataset.upstreams=signature}const render=c=>{currentConfig=c;renderSavedUpstreams(c);syncOpenNetwork();q('#network')."
        "innerHTML='<article class=status-card><h2>Upstream</h2><b>'+(c.connected?'Connected':'Not connected')+'</b><span>IP: '+(c.ip||'—')+'</span><span>Gateway: '+(c.gateway||'—')+'</span><span>DNS: '+(c.dns||'—')+'</span></article><article class=status-card><h2>Routing</h2><span>Mode: '+c.mode+'</span><span>Upload: '+rate(c.up_bps)+'</span><span>Download: '+rate(c.down_bps)+'</span><span>Rolling 10s up/down: '+rate(c.up_bps_10s)+' / '+rate(c.down_bps_10s)+'</span><span>Rolling 30s up/down: '+rate(c.up_bps_30s)+' / '+rate(c.down_bps_30s)+'</span></article><article class=status-card><h2>Tunnel</h2><span>XUDP: '+c.xudp_active+'/56</span><span>Queue: '+c.xudp_queued+'/160, drops: '+c.xudp_dropped+'</span><span>Mux: '+(c.singmux_enabled?(c.singmux_connected?'connected':'waiting'):'off')+'</span><span>TCP streams: '+c.singmux_tcp_active+'/'+c.transparent_tcp_max+'</span><span>Sessions open/closed: '+c.singmux_sessions_opened+'/'+c.singmux_sessions_closed+' (EOF '+c.singmux_close_eof+', protocol '+c.singmux_close_protocol_error+')</span><span>TCP RX queue: high '+c.singmux_tcp_rx_queue_high_water+'/24, full '+c.singmux_tcp_rx_queue_full+'</span></article><article class=status-card><h2>Device</h2><span>CPU clock: '+c.cpu_frequency_mhz+' MHz</span><span>Chip: '+c.chip_temperature_c.toFixed(1)+' °C</span><span>CPU core 0: '+c.cpu_load_core0+'%</span><span>CPU core 1: '+c.cpu_load_core1+'%</span></article><article class=status-card><h2>Memory</h2><span>Internal free: '+size(c.free_internal)+'</span><span>Largest internal block: '+size(c.largest_internal_block)+'</span><span>PSRAM free: '+size(c.free_psram)+'</span><span>Total free: '+size(c.free_total)+'</span></article>';let route=c.mode==='transparent-upstream'?'direct':'vless',history=histories[route],label=route==='direct'?'Direct':'VLESS';q('#bandwidth_title').textContent=label+' payload bandwidth';history.push({up:c.up_bps,down:c.down_bps,xudp:"
        "c.xudp_active,queue:c.xudp_queued,mux:c.singmux_tcp_active});if(history.length>"
        "historyLimit)"
        "history.shift();deviceHistory.push({temperature:c.chip_temperature_c,cpu0:c.cpu_load_core0,cpu1:c.cpu_load_core1});if(deviceHistory.length>historyLimit)deviceHistory.shift();chart('temperature_chart',['Chip °C'],['#dc2626'],deviceHistory.map(x=>x.temperature));chart('cpu_chart',['Core 0','Core 1'],['#2563eb','#7c3aed'],deviceHistory.map(x=>x.cpu0),deviceHistory.map(x=>x.cpu1));chart('bandwidth_chart',['Upload','Download'],['#d97706','#0b6e4f'],"
        "history.map(x=>x.up),history.map(x=>x.down));chart('pressure_chart',['XUDP associations',"
        "'Ingress queue','Mux TCP streams'],['#2563eb','#d97706','#7c3aed'],history.map(x=>x.xudp),"
        "history.map(x=>x.queue),history.map(x=>x.mux));q('#bandwidth_summary').textContent='Last "
        "'+history.length+' seconds ('+label+'): upload '+rate(c.up_bps)+', download '+rate(c.down_bps)+'.';"
        "q('#temperature_summary').textContent='Current chip temperature: '+c.chip_temperature_c.toFixed(1)+' °C.';q('#cpu_summary').textContent='Current CPU: core 0 '+c.cpu_load_core0+'%, core 1 '+c.cpu_load_core1+'%.';"
        "q('#pressure_summary').textContent='Current: '+c.xudp_active+' XUDP associations, '+"
        "c.xudp_queued+' queued datagrams, '+c.singmux_tcp_active+' mux TCP streams.';"
        "q('#version').textContent='Firmware: '+c.firmware_version};function "
        "chart(id,names,colors,..."
        "sets){let "
        "e=q('#'+id),d=devicePixelRatio||1,w=e.clientWidth||300,h=e.clientHeight||145;if(e.width"
        "!=w*d||e.height!=h*d){e.width=w*d;e.height=h*d}let "
        "x=e.getContext('2d');x.setTransform(d,0,0,d,0,0);"
        "x.clearRect(0,0,w,h);let "
        "all=sets.flat(),top=Math.max(1,...all),pad=24;x.strokeStyle='#d8dee6';"
        "x.lineWidth=1;for(let i=0;i<4;i++){let "
        "y=pad+i*(h-pad-30)/3;x.beginPath();x.moveTo(pad,y);x.lineTo(w,y);"
        "x.stroke()}x.fillStyle='#59636e';x.font='11px "
        "system-ui';x.fillText(top>=1024?(top/1024).toFixed(1)+'K':top,"
        "0,pad+4);x.fillText('0',8,h-18);sets.forEach((set,j)=>{if(!set.length)return;x."
        "strokeStyle=colors[j];"
        "x.lineWidth=2;x.beginPath();set.forEach((v,i)=>{let "
        "px=pad+(w-pad-4)*(i/Math.max(1,historyLimit-1)),"
        "py=pad+(h-pad-30)*(1-v/top);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()});let lx=pad;"
        "names.forEach((name,i)=>{x.fillStyle=colors[i];x.fillRect(lx,4,9,9);x.fillStyle='#59636e';"
        "x.fillText(name,lx+13,"
        "13);lx+=x.measureText(name).width+30})}async function load(){let c=await(await "
        "fetch('/api/config',{cache:'no-store'})).json();for(let k in c){let "
        "e=q('#'+k);if(e){if(e.type==='checkbox')e.checked=!!c[k];else "
        "e.value=c[k]||''}}render(c);if(Array.isArray(c.scan_results))showNetworks(q('#net'),c.scan_results)}function showNetworks(s,n){if(!Array.isArray(n))throw Error('Invalid scan response');s.options.length=0;if(n.length){s.add(new Option('Select a network',''));n.forEach(x=>{s.add(new Option(x.ssid+' ('+x.rssi+' dBm)',x.ssid))})}else s.add(new Option('No networks found',''));st.textContent='Found '+n.length+' network(s).'}async function scan(){let s=q('#net');scanInProgress=true;s.options.length=0;"
        "s.add(new Option('Scanning networks...',''));s.disabled=true;st.textContent='Scanning...';try{let "
        "r=await fetch('/api/scan',{cache:'no-store'});if(!r.ok)throw Error(await r.text());showNetworks(s,await r.json())}catch(e){st.textContent='Scan completed; reloading saved results...';setTimeout(()=>location.reload(),2500)}finally{s.disabled=false;scanInProgress=false}}async function "
        "save(url,names){try{let d=new URLSearchParams;names.forEach(n=>{let "
        "e=q('#'+n);d.append(n,e.type==='checkbox'?(e.checked?'1':'0'):e.value)});let r=await "
        "fetch(url,{method:'POST',headers:{'Content-Type':'application/"
        "x-www-form-urlencoded'},body:d});if(!r.ok)throw Error(await "
        "r.text());st.textContent=(await "
        "r.json()).message;setTimeout(load,1000)}catch(e){st.textContent='Save failed: "
        "'+e.message}}async function delUpstream(){let ssid=q('#saved_upstreams').value||q('#ssid').value;if(!ssid){st.textContent='Select a saved upstream to delete.';return}if(!confirm('Delete saved upstream '+ssid+'?'))return;try{let d=new URLSearchParams;d.append('ssid',ssid);let r=await fetch('/api/upstream-delete',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:d});if(!r.ok)throw Error(await r.text());st.textContent=(await r.json()).message;setTimeout(load,1000)}catch(e){st.textContent='Delete failed: '+e.message}}q('#scan').onclick=scan;q('#open_network').onchange=syncOpenNetwork;q('#saved_upstreams').onchange=e=>{let v=e.target.value,x=(currentConfig&&currentConfig.upstream_networks||[]).find(n=>n.ssid===v);if(!x)return;q('#ssid').value=x.ssid;q('#open_network').checked=!!x.open;syncOpenNetwork();q('#password').value=''};q('#net').onchange=e=>{q('#ssid').value=e.target.value;q('#open_network').checked=false;syncOpenNetwork()};q('#save_ap').onclick=()=>save('/api/"
        "access-point',['ap_ssid','ap_password','ap_ip']);q('#save_upstream').onclick=()=>save('/api/"
        "upstream',['ssid','password','open_network']);q('#delete_upstream').onclick=delUpstream;q('#save_admin_password').onclick=()=>save('/api/"
        "admin-password',"
        "['current_admin_password','new_admin_password']);q('#save_vless').onclick=()=>save('/api/"
        "vless',['vless_uri','host','port','uuid','dns_resolver','singmux_enabled']);q('#install_"
        "ota')."
        "onclick=async()=>{let f=q('#ota_file').files[0];if(!f){st.textContent='Choose an OTA .bin "
        "file first.';return}if(!confirm('Install '+f.name+' and reboot the router?'))return;"
        "st.textContent='Uploading firmware; keep this page open...';try{let r=await "
        "fetch('/api/ota',"
        "{method:'POST',headers:{'Content-Type':'application/"
        "octet-stream'},body:f});if(!r.ok)throw "
        "Error(await r.text());st.textContent=(await "
        "r.json()).message}catch(e){st.textContent='OTA "
        "update failed: '+e.message}};load();"
        "setInterval(()=>{if(scanInProgress||refreshInProgress)return;refreshInProgress=true;fetch('/api/"
        "config',{cache:'no-store'}).then(r=>r.json()).then(render).catch(()=>q('#network')."
        "textContent='Router status refresh failed').finally(()=>refreshInProgress=false)},1000);</script></body></html>";
    return page;
}
